on:
  workflow_call:
name: Deploy cluster
inputs:
    gh_token:
      description: Secret github
      require: true
runs: 
  using: 'composite'
  steps:
    - name: Deploy cluster
      shell: bash
      run: |
        # selecionar contexto do kubernetes
        kubectl config use-context local

        # verificar se o namespace existe
        if [ "$(kubectl get ns --no-headers -o custom-columns=":metadata.name" | grep ${{ env.environment }}-${{ env.namespace }})" != "${{ env.environment }}-${{ env.namespace }}" ];then
          echo -e "\033[32m\033[1m  kubectl create ns ${{ env.namespace }}"
          kubectl create ns ${{ env.environment }}-${{ env.namespace }}
        else
          echo -e "\033[32m\033[1m NAMESPACE ${{ env.environment }}-${{ env.namespace }} ja existe"
        fi

        # clonar um repositorio da aplicacao
        git clone https://devops-pro-mota:${{inputs.gh_token}}@github.com/devops-pro-mota/ALM-k8s.git
        cd ALM-k8s
        kubectl apply -f ${{ env.namespace }}/${{ github.event.repository.name }}/${{ env.environment }}
