on:
  workflow_call:
name: Deploy cluster
inputs:
    gh_token:
      description: Secret github
      require: true
runs: 
  using: 'composite'
  steps:
    - name: Deploy cluster
      shell: bash
      run: |
        # selecionar contexto do kubernetes
        kubectl config use-context local

        # verificar se o namespace existe
        if [ "$(kubectl get ns --no-headers -o custom-columns=":metadata.name" | grep ${{ env.environment }}-${{ env.namespace }})" != "${{ env.environment }}-${{ env.namespace }}" ];then
          echo -e "\033[32m\033[1m  kubectl create ns ${{ env.namespace }}"
          kubectl create ns ${{ env.environment }}-${{ env.namespace }}
        else
          echo -e "\033[32m\033[1m NAMESPACE ${{ env.environment }}-${{ env.namespace }} ja existe"
        fi

        # clonar um repositorio da aplicacao
        git clone https://devops-pro-mota:${{inputs.gh_token}}@github.com/devops-pro-mota/ALM-k8s.git
        # entrar no diretorio dos manifestos
        cd ALM-k8s/${{ env.namespace }}/${{ github.event.repository.name }}/${{ env.environment }}

        # encontrar a ocorrencia da imagem e alterar o build
        #sed -i 's/rodrigomotadevops\/${{ env.environment }}-${{ github.event.repository.name }}:/rodrigomotadevops\/${{ env.environment }}-${{ github.event.repository.name }}:/g' seu_arquivo.yml
        sed -E -i 's/${{ github.event.repository.name }}:[0-9]+/${{ github.event.repository.name }}:'$GITHUB_RUN_ID/g deployments.yml
        cd ../../../
        # comitar alteracoes no repositorio
        git config --global user.email "rodrigommota17@gmail.com"
        git config --global user.name "rodrigomotadevops"
        git add .
        git commit -m "Alterando imagem para ${{ github.event.repository.name }}:$GITHUB_RUN_ID"
        git push


        kubectl apply -f . --recursive
