on:
  workflow_call:
name: Deploy cluster
inputs:
    gh_token:
      description: Secret github
      require: true
runs: 
  using: 'composite'
  steps:
    - name: Deploy cluster
      env:
        TOKEN: ${{inputs.gh_token}}
      shell: bash
      run: |
        # selecionar contexto do kubernetes
        kubectl config use-context local
        
        # verificar se o namespace existe
        if [ "$(kubectl get ns --no-headers -o custom-columns=":metadata.name" | grep ${{ env.environment }}-${{ env.namespace }})" != "${{ env.environment }}-${{ env.namespace }}" ];then
          echo -e "\033[32m\033[1m  kubectl create ns ${{ env.namespace }}"
          kubectl create ns ${{ env.environment }}-${{ env.namespace }}
        else
          echo -e "\033[32m\033[1m NAMESPACE ${{ env.environment }}-${{ env.namespace }} ja existe"
        fi
        # controla a versao do ingress
        sed -E -i 's/Versao-RetryBuild=[0-9]+/Versao-RetryBuild='$GITHUB_RUN_NUMBER/g ingress.yml
        
        # clonar um repositorio da aplicacao
        git clone https://devops-pro-mota:${{inputs.gh_token}}@github.com/devops-pro-mota/ALM-k8s.git
        # entrar no diretorio dos manifestos
        cd ALM-k8s/${{ env.namespace }}/${{ github.event.repository.name }}/${{ env.environment }}

        # encontrar a ocorrencia da imagem e alterar o build
        #sed -i 's/rodrigomotadevops\/${{ env.environment }}-${{ github.event.repository.name }}:/rodrigomotadevops\/${{ env.environment }}-${{ github.event.repository.name }}:/g' seu_arquivo.yml

        # baixar a imagem do docker hub referente a gmud aprovada 
        if ! [ -z "${{ github.event.inputs.Gmud }}" ]
        then
          IMAGE_BUILD_ID=$(curl -k -X 'GET' 'https://192.168.0.93:32776/api/Changes/getBuildIDGmud?gmud=${{ github.event.inputs.Gmud }}&recurso=${{ github.event.repository.name }}' -H 'accept: text/plain')
          echo "IMAGE_BUILD_ID=$(echo $IMAGE_BUILD_ID)" >> $GITHUB_ENV
          sed -E -i 's/${{ github.event.repository.name }}:[0-9]+/${{ github.event.repository.name }}:'$IMAGE_BUILD_ID/g deployments.yml
          kubectl apply -f . --recursive
        else
          sed -E -i 's/${{ github.event.repository.name }}:[0-9]+/${{ github.event.repository.name }}:'$GITHUB_RUN_ID/g deployments.yml
          kubectl apply -f . --recursive    
        fi  
        
        cd ../../../
        #echo pwd
        # comitar alteracoes no repositorio
        git config --global user.email "rodrigommota17@gmail.com"
        git config --global user.name "rodrigomotadevops"
      
        git add .
        # baixar a imagem do docker hub referente a gmud aprovada 
        if ! [ -z "${{ github.event.inputs.Gmud }}" ]
        then
          git commit -m "Alterando imagem homologada GMUD ${{ github.event.repository.name }}:"$IMAGE_BUILD_ID
        else 
          git commit -m "Alterando imagem para ${{ github.event.repository.name }}:"$GITHUB_RUN_ID
        fi  

        git push git@github.com:devops-pro-mota/ALM-k8s.git main

        
