on:
  workflow_call:
name: Find Credentials
runs: 
  using: 'composite'
  steps:
    - name: Find Credentials
      shell: bash
      run: |
          rm -rf resultado.txt
          # Iterar sobre todos os arquivos no diretório
          export retorno=$(find . -type f -exec grep -H -E -i "database=[a-zA-Z0-9./?=_-]|server=[a-zA-Z0-9./?=_-]|password=[a-zA-Z0-9./?=_-]|user=[a-zA-Z0-9./?=_-]|Usuario=[a-zA-Z0-9./?=_-]" {} + > resultado.txt ) 
          echo "Credenciais encontradas"
          echo "$retorno"

          
           if [ -f resultado.txt ]; then
            if [ -s resultado.txt ]; then
              echo "O arquivo resultado.txt existe e tem conteúdo. Cancelando execução da action."
              cat resultado.txt
              exit 1
            else
              echo "O arquivo resultado.txt existe, mas está vazio."
              cat resultado.txt
            fi
          else
            echo "O arquivo resultado.txt não existe."
          fi
  
          echo "-------------------------------------------------------"
          echo "procurando urls"
          find . -type f -exec grep -H -E -i "(http|https)://[a-zA-Z0-9./?=_-]*" {} +
