on:
  workflow_call:
name: Find Credentials
runs: 
  using: 'composite'
  steps:
    - name: Find Credentials
      shell: bash
      run: |
          export diretorio="."
          # Iterar sobre todos os arquivos no diretório
          for arquivo in $diretorio/*; do
              # Verificar se o arquivo é um arquivo de texto
              if [[ -f $arquivo && $(file -b --mime-type "$arquivo") == "text/plain" ]]; then
                  # Usar o grep para procurar por URLs no conteúdo do arquivo
                  urls=$(grep -Eo "https?://[^[:space:]]+" "$arquivo")
                  arquivos$(grep -Er "database=[a-zA-Z0-9./?=_-]|server[a-zA-Z0-9./?=_-]|password=[a-zA-Z0-9./?=_-]|User=[a-zA-Z0-9./?=_-]|Usuario=[a-zA-Z0-9./?=_-]" .)
           
                  # Imprimir URLs encontradas
                  if [[ ! -z $urls ]]; then
                      echo "URLs encontradas no arquivo $arquivo:"
                      echo "$urls"
                      echo "$arquivos"
                      echo "-----------------------------"
                  fi
              fi
          done
