on:
  workflow_call:
name: Find Credentials
runs: 
  using: 'composite'
  steps:
    - name: Find Credentials
      shell: bash
      run: |
          export diretorio="."
          # Iterar sobre todos os arquivos no diretório
          find . -type f -exec grep -H -E -i "(http|https)://[a-zA-Z0-9./?=_-]*" {} +
