on:
  workflow_call:
name: Bem sucedido
runs: 
  using: 'composite'
  steps:
      - uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.x

      - name: Cache SonarCloud packages
        uses: actions/cache@v1
        with:
          path: ~\sonar\cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache SonarCloud scanner
        id: cache-sonar-scanner
        uses: actions/cache@v1
        with:
          path: .\.sonar\scanner
          key: ${{ runner.os }}-sonar-scanner
          restore-keys: ${{ runner.os }}-sonar-scanner

      - name: Install SonarCloud scanner
        if: steps.cache-sonar-scanner.outputs.cache-hit != 'true'
        run: dotnet tool update dotnet-sonarscanner --tool-path ./.sonar/scanner

      - name: Install project dependencies
        run: dotnet restore

      - name: Test and analyze
        env:
          #GITHUB_TOKEN: ${{ secrets.GITHUBDEV_TOKEN }}
          SONAR_TOKEN: sqp_ebcfbc9ac0e70a5db84829a99903971ca59c1c2f
        run: |
            ./.sonar/scanner/dotnet-sonarscanner begin /k:"sonar" /d:sonar.token="sqp_ebcfbc9ac0e70a5db84829a99903971ca59c1c2f" /d:sonar.host.url="http://192.168.0.201:9000"
              dotnet build
            ./.sonar/scanner/dotnet-sonarscanner end /d:sonar.token="sqp_ebcfbc9ac0e70a5db84829a99903971ca59c1c2f"

      - name: Build
        run: dotnet build --configuration Release --no-restore
