on:
  workflow_call:
name: Sonar
runs: 
  using: 'composite'
  steps:
    - name: pipeline metrics
      shell: bash
      run: |
          cd /home/gitlab/.dotnet/tools/.store/dotnet-sonarscanner/5.15.0/dotnet-sonarscanner/5.15.0/tools/netcoreapp3.0/any
          ./sonar-scanner-4.8.1.3023/bin/sonar-scanner -X -D sonar.projectKey=api
