on:
  workflow_call:
name: Bem sucedido
runs: 
  using: 'composite'
  steps:
    - name: Bem sucedido
      shell: bash
      run: |
          echo "Ambiente do deploy ${{ env.environment }}"
          echo "RUN ID $GITHUB_RUN_ID"
          echo "REPO NAME: $GITHUB_REPOSITORY"
          projeto=$(echo "$GITHUB_REPOSITORY") | cut -d "/" -f 2
          projeto=${GITHUB_REPOSITORY##*/}
          echo "Nome repo: ${{env.reponame}}"

          echo "Projeto: $projeto"
          echo "Branch: $GITHUB_REF_NAME"
          echo "Status: $GITHUB_RUN_STATUS"
          echo "Usuario: $GITHUB_TRIGGERING_ACTOR"
 
          
          # atualizar api de metrics
          echo "PUT API"
          curl -k -X 'PUT' \
                    'https://192.168.0.93:32776/api/Evento/$GITHUB_RUN_ID' \
                    -H 'accept: text/plain' \
                    -H 'Content-Type: application/json' \
                    -d '{
                          "buildId": "'$GITHUB_RUN_ID'",
                          "nomeJob": "${{github.workflow}}",
                          "statusRun": "sucess"
                        }'

          # se tiver var de gmud enviar suscesso para API para
          if ! [ -z "${{ github.event.inputs.Gmud }}" ]
          then
            echo "Gmud não informada."
          else
            echo "Gmud informada: [ ${{ github.event.inputs.Gmud }} ]"
            IMAGE_BUILD_ID=$(curl -k -X 'GET' 'https://192.168.0.93:32776/api/Changes/getBuildIDGmud?gmud=${{ github.event.inputs.Gmud }}&recurso=${{ github.event.repository.name }}' -H 'accept: text/plain')
            echo "IMAGE_BUILD_ID=$(echo $IMAGE_BUILD_ID)" >> $GITHUB_ENV

            curl -k -X 'PUT' \
                      'https://192.168.0.93:32776/api/Evento/$GITHUB_RUN_ID' \
                      -H 'accept: text/plain' \
                      -H 'Content-Type: application/json' \
                      -d '{
                            "id": 0,
                            "buildid": "'$IMAGE_BUILD_ID'",
                            "statusExecucao": "sucesso"
                          }' 

          fi
