on:
  workflow_call:
name: Bem sucedido
runs: 
  using: 'composite'
  steps:
    - name: Bem sucedido
      env: 
        job_name: $GITHUB_JOB 
      shell: bash
      run: |
          echo "Ambiente do deploy ${{ env.environment }}"
          echo "RUN ID $GITHUB_RUN_ID"
          echo "REPO NAME: $GITHUB_REPOSITORY"
          projeto=$(echo "$GITHUB_REPOSITORY") | cut -d "/" -f 2
          projeto=${GITHUB_REPOSITORY##*/}

          echo "Projeto: $projeto"
          echo "Branch: $GITHUB_REF_NAME"
          echo "Status: $GITHUB_RUN_STATUS"
          echo "Usuario: $GITHUB_TRIGGERING_ACTOR"
          
          # atualizar api de metrics
          echo "PUT API"
          curl -X 'PUT' \
                    'https://dev-api-gestao.purecloud.com.br/api/Evento/$GITHUB_RUN_ID' \
                    -H 'accept: text/plain' \
                    -H 'Content-Type: application/json' \
                    -d '{
                          "buildId": "'$GITHUB_RUN_ID'",
                          "statusRun": "failed"
                        }'
          # se tiver var de gmud enviar suscesso para API para
          if  [ -z "${{ github.event.inputs.Gmud }}" ]
          then
            echo "Gmud não informada."
          else  
            echo "Gmud informada: [ ${{ github.event.inputs.Gmud }} ]"
            IMAGE_BUILD_ID=$(curl -X 'GET' 'https://dev-api-gestao.purecloud.com.br/api/Changes/getBuildIDGmud?gmud=${{ github.event.inputs.Gmud }}&recurso=${{ github.event.repository.name }}' -H 'accept: text/plain')
            echo "IMAGE_BUILD_ID=$(echo $IMAGE_BUILD_ID)" >> $GITHUB_ENV
            
            curl -X 'PUT' \
                      'https://dev-api-gestao.purecloud.com.br/api/Changes/updExecucaoChange' \
                      -H 'accept: text/plain' \
                      -H 'Content-Type: application/json' \
                      -d '{
                            "id": ${{ github.event.inputs.Gmud }},
                            "buildid": "'$IMAGE_BUILD_ID'",
                            "newBuildID":"'$GITHUB_RUN_ID'",
                            "statusExecucao": "failed"
                          }'
          fi       

            curl -X 'POST' \
                      'https://dev-api-gestao.purecloud.com.br/api/EventosLog' \
                      -H 'accept: text/plain' \
                      -H 'Content-Type: application/json' \
                      -d '{
                            "id": 0,
                              "buildid": "'$GITHUB_RUN_ID'",
                              "recurso": "'${{ github.event.repository.name }}'",
                              "ambiente": "'${{ env.environment }}'",
                              "erroMsg": "Erro na etapa de: '${{ env.job_name }}'"
                          }'
