on:
  workflow_call:
name: SAST com Trivy
runs: 
  using: 'composite'
  steps:
    - name: Find Credentials
      shell: bash
      run: |
 
          # Execute o Trivy e obtenha o resumo dos resultados em formato Text/Plain. Tentei Json mas não consegui
          # Observação: este comando pressupõe que Trivy já está instalado e configurado na máquina local
          touch trivy_results.json
          trivy image rodrigomotadevops/${{ env.environment }}-${{ github.event.repository.name }}:$GITHUB_RUN_ID > trivy_results.json
          # trivy image rodrigomotadevops/${{ env.environment }}-${{ github.event.repository.name }}:$GITHUB_RUN_ID # > trivy_results.json
          echo trivy image rodrigomotadevops/${{ env.environment }}-${{ github.event.repository.name }}:$GITHUB_RUN_ID
          # Use o jq para contar as entradas CVEs no JSON
          # Instale o jq caso ainda não esteja instalado na sua máquina
    

          # Use o comando sed para extrair os valores e atribuí-los às variáveis
          UNKNOWN=$(cat trivy_results.json | sed -n 's/.*UNKNOWN: \([0-9]*\).*/\1/p' | head -n 1)
          LOW=$(cat trivy_results.json | sed -n 's/.*LOW: \([0-9]*\).*/\1/p' | head -n 1)
          MEDIUM=$(cat trivy_results.json | sed -n 's/.*MEDIUM: \([0-9]*\).*/\1/p' | head -n 1)
          HIGH=$(cat trivy_results.json | sed -n 's/.*HIGH: \([0-9]*\).*/\1/p' | head -n 1)
          CRITICAL=$(cat trivy_results.json | sed -n 's/.*CRITICAL: \([0-9]*\).*/\1/p' | head -n 1)
          
          # Echo the values to verify that they're correct
          echo "UNKNOWN: $UNKNOWN"
          echo "LOW: $LOW"
          echo "MEDIUM: $MEDIUM"
          echo "HIGH: $HIGH"
          echo "CRITICAL: $CRITICAL"
          TOTAL=$(($UNKNOWN + $LOW + $MEDIUM + $HIGH + $CRITICAL))
          # Exportação da contagem de CVEs para um arquivo
          echo "Quantidade de CVEs: $TOTAL" 
          
          curl -X 'PUT' \
            'https://dev-api-gestao.purecloud.com.br/api/Analitics/0' \
            -H 'accept: text/plain' \
            -H 'Content-Type: application/json' \
            -d '{
            "id": 0,
            "nomeRepositorio": "'${{ github.event.repository.name }}'",
            "cve_low": '"${LOW}"',
            "cve_medium": '"${MEDIUM}"',
            "cve_high": '"${HIGH}"',
            "cve_critical": '"${CRITICAL}"'        
             }'

          #echo curl -X 'PUT' 'https://dev-api-gestao.purecloud.com.br/api/Analitics/0' -H 'accept: text/plain' -H 'Content-Type: application/json' -d '{ "id": 0,"nomeRepositorio": "worker-processa-repo","cve_low": ${LOW},"cve_medium": $LOW,"cve_high": 5,"cve_critical": 10 }'
          #curl -X 'PUT' 'https://dev-api-gestao.purecloud.com.br/api/Analitics/0' -H 'accept: text/plain' -H 'Content-Type: application/json' -d '{ "id": 0,"nomeRepositorio": "worker-processa-repo","cve_low": ${LOW},"cve_medium": $LOW,"cve_high": 5,"cve_critical": 10 }'
          
          cat trivy_results.json
          
          # Remova o arquivo JSON caso não queira mantê-lo
          # rm trivy_results.json
          
              
