on:
  workflow_call:
name: Docker pull 
runs: 
  using: 'composite'
  steps:
    - name: pipeline metrics
      shell: bash
      run: |
         docker pull rodrigomotadevops/${{ env.environment }}-${{ github.event.repository.name }}:$GITHUB_RUN_ID
  
  
