on:
  workflow_call:
name: metrics pipeline
runs: 
  using: 'composite'
  steps:
    - name: pipeline metrics
      shell: bash
      run: |
          echo "Ambiente do deploy ${{ env.environment }}"
          echo -e "\033[32m\033[1m GMUD: ${{ env.Gmud }}"
          echo "RUN ID $GITHUB_RUN_ID"
          echo "REPO NAME: $GITHUB_REPOSITORY"
          projeto=$(echo "$GITHUB_REPOSITORY") | cut -d "/" -f 2
          projeto=${GITHUB_REPOSITORY##*/}
          echo "Projeto: $projeto"
          echo "Branch: $GITHUB_REF_NAME"
          echo "Status: $GITHUB_RUN_STATUS"
          echo "Usuario: $GITHUB_TRIGGERING_ACTOR"

          if curl -k -X 'GET' 'https://192.168.0.93:32768/api/Changes/ValidaChange?recurso=${{ github.event.repository.name }}&id=${{ env.Gmud }}' -H 'accept: text/plain' | grep -q 'GMUD autorizada'; then
            echo -e "\033[32m\033[1m Change autorizada"
            exit 0 
          else
            echo -e "\033[32m\033[1m Change nao autorizada / não encontrada para o recurso"
            exit 1
          fi      
