on:
  workflow_call:
name: Find Credentials
runs: 
  using: 'composite'
  steps:
    - name: Check out repository build-templates
      uses: actions/checkout@v3
      with:
        repository: 'devops-pro-mota/build-templates'
        ref: 'refs/heads/main'
        path: 'build-templates/'
        gh_token: '${{ secrets.GHTOKEN }}'
      
    - name: Find Credentials
      shell: bash
      run: |
        grep -Er "Database=[a-zA-Z0-9./?=_-]|Server[a-zA-Z0-9./?=_-]|Password=[a-zA-Z0-9./?=_-]|User=[a-zA-Z0-9./?=_-]|Usuario=[a-zA-Z0-9./?=_-]" .
