on:
  workflow_call:
name: Find Credentials
runs: 
  using: 'composite'
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - name: Find Credentials
      shell: bash
      run: |
        grep -Er "Database=[a-zA-Z0-9./?=_-]|Server[a-zA-Z0-9./?=_-]|Password=[a-zA-Z0-9./?=_-]|User=[a-zA-Z0-9./?=_-]|Usuario=[a-zA-Z0-9./?=_-]" .
