on:
  workflow_call:
name: Docker Build, Tag and Push
runs: 
  using: 'composite'
  steps:
    
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: rodrigomotadevops
          password: dckr_pat_NF9HXp4eKZdFKHMrZFBtx5sS6wA

      - name: pipeline metrics
        shell: bash
        run: |
          docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7 -t rodrigomotadevops/${{ env.environment }}-${{ github.event.repository.name }}:latest --push .
          docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7 -t rodrigomotadevops/${{ env.environment }}-${{ github.event.repository.name }}:$GITHUB_RUN_ID --push .
