on:
  workflow_call:
name: Docker Build, Tag and Push
runs: 
  using: 'composite'
  steps:
    
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: rodrigomotadevops
          password: dckr_pat_NF9HXp4eKZdFKHMrZFBtx5sS6wA

      - name: pipeline metrics
        shell: bash
        run: |
            # baixar a imagem do docker hub referente a gmud aprovada 
            if ! [ -z "${{ github.event.inputs.Gmud }}" ]
            then
              IMAGE_BUILD_ID=$(curl -k -X 'GET' 'https://192.168.0.93:32776/api/Changes/getBuildIDGmud?gmud=${{ github.event.inputs.Gmud }}&recurso=${{ github.event.repository.name }}' -H 'accept: text/plain')
              echo "IMAGE_BUILD_ID=$(echo $IMAGE_BUILD_ID)" >> $GITHUB_ENV

              if [ -z "$IMAGE_BUILD_ID" ]
              then
                echo "IMAGE_BUILD_ID is empty, erro ao obter o ID da imagem do docker hub referente a gmud aprovada"
                exit 1
              else
                echo "IMAGE_BUILD_ID is not empty"
                docker pull rodrigomotadevops/hml-${{ github.event.repository.name }}:$IMAGE_BUILD_ID 
                docker tag rodrigomotadevops/hml-${{ github.event.repository.name }}:$IMAGE_BUILD_ID rodrigomotadevops/prd-${{ github.event.repository.name }}:$IMAGE_BUILD_ID 
                docker push rodrigomotadevops/prd-${{ github.event.repository.name }}:$IMAGE_BUILD_ID
              fi
            else
              echo "Gmud não informada."
                # docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7 -t rodrigomotadevops/${{ env.environment }}-${{ github.event.repository.name }}:latest --push .
                cd api-gestao
                docker buildx build -t rodrigomotadevops/${{ env.environment }}-${{ github.event.repository.name }}:$GITHUB_RUN_ID --push .
            fi
