on:
  workflow_call:
name: Docker Build and Push
runs: 
  using: 'composite'
  steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - run: |
            echo "Env: ${{ github.event.inputs.environment }}" 
            echo "Branch: ${{ github.event.inputs.branch }}"
      - name: Check out repository build-templates
        uses: actions/checkout@v3
        with:
          repository: 'devops-pro-mota/build-templates'
          ref: 'refs/heads/main'
          #token: '${{ secrets.GH_TOKEN }}'
          path: 'build-templates/'
          
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: rodrigomotadevops
          password: dckr_pat_NF9HXp4eKZdFKHMrZFBtx5sS6wA

      - name: pipeline metrics
        shell: bash
        run: |
          docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7 -t rodrigomotadevops/${{ env.environment }}-${{ env.projeto }}:2024 --push .
