name: ci-cd-csharp
on:
  workflow_dispatch:
  workflow_call:
    inputs:
      Gmud:
        type: string
      environment:
        required: true
        type: string
      namespace:
        required: true
        type: string  

jobs:

    Validate:
      runs-on: Linux
      steps:
        - run: |
            echo "Env: ${{ github.event.inputs.environment }}" 
            echo "Branch: ${{ github.event.inputs.branch }}"
        - name: Check out repository build-templates
          uses: actions/checkout@v3
          with:
            repository: 'devops-pro-mota/build-templates'
            ref: 'refs/heads/main'
            path: 'build-templates/'
            gh_token: '${{ secrets.GHTOKEN }}'
          
         # metricas
        - uses: ./build-templates/.github/workflows/actions/validacoes
          name: Metrics Pipeline
          env:      
            solution: ${{ github.event.inputs.solution }}
            environment: ${{ github.event.inputs.environment }}
            namespace: ${{ github.event.inputs.namespace }}  

          # adiciona step para validar sonar
        - uses: ./build-templates/.github/workflows/actions/sonar
          name: Sonar Validate 

          # adiciona step para validar find credentials
        - uses: ./build-templates/.github/workflows/actions/find-credendials
          name: Find Credentials             
    

    pipeline-build-dev:
      runs-on: Linux
      needs: Validate
      if: ${{ github.event.inputs.environment == 'dev' }}
      steps:
        - name: Check out repository
          uses: actions/checkout@v3
        - name: Check out repository build-templates
          uses: actions/checkout@v3
          with:
            repository: 'devops-pro-mota/build-templates'
            ref: 'refs/heads/main'
            path: 'build-templates/'
            gh_token: '${{ secrets.GHTOKEN }}'


        #   # normaliza as variaveis de ambiente  
        # - name: Variaveis iniciais
        #   uses: ./build-templates/.github/workflows/actions/vars
        #   env:      
        #     environment: ${{ github.event.inputs.environment }}
        #     namespace: ${{ github.event.inputs.namespace }}
            
   
            
          # executa step docker build e push
        - uses: ./build-templates/.github/workflows/release/docker-hub
          name: Docker Build and Push (Release)
          env:      
            environment: ${{ github.event.inputs.environment }}
            projeto: ${{ github.event.repository.name }}
            gh_token: '${{ secrets.GHTOKEN }}'

          #executar step apenas se der erro 
        - uses: ./build-templates/.github/workflows/actions/falha
          name: Falha de execução
          if: ${{ failure() }}
          env:      
            environment: ${{ github.event.inputs.environment }}
            Gmud: ${{ github.event.inputs.Gmud }}
          # executa step apenas se der sucesso
        - uses: ./build-templates/.github/workflows/actions/sucesso
          name: Sucesso de execução
          if: ${{ success() }}
          env:      
            environment: ${{ github.event.inputs.environment }}
            Gmud: ${{ github.event.inputs.Gmud }}


    deploy-k8s-dev:
      runs-on: linux
      needs: pipeline-build-dev
      steps:
        - name: Check out repository
          uses: actions/checkout@v3
        - run: |
            echo "Env: ${{ github.event.inputs.environment }}" 
            echo "Branch: ${{ github.event.inputs.branch }}"
        - name: Check out repository build-templates
          uses: actions/checkout@v3
          with:
            repository: 'devops-pro-mota/build-templates'
            ref: 'refs/heads/main'
            gh_token: '${{ secrets.GHTOKEN }}'
            path: 'build-templates/'

          # deploy k8s
        - name: Deploy Cluster k8s
          uses: ./build-templates/.github/workflows/release/kubectl
          env:      
            environment: ${{ github.event.inputs.environment }}
            namespace: ${{ github.event.inputs.namespace }}
            gh_token: '${{ secrets.GHTOKEN }}'      

    # deploy-k8s-dev:
    #   runs-on: linux
    #   needs: deploy-docker-dev
    #   steps:
    #       # normaliza as variaveis de ambiente  
    #     - name: Deploy cluster k8s
    #       uses: ./build-templates/.github/workflows/actions/vars


    pipeline-build-hml:
      runs-on: linux
      needs: Validate
      if: ${{ github.event.inputs.environment == 'hml' }}
      steps:
        - name: Check out repository
          uses: actions/checkout@v3
        - run: |
            echo "Env: ${{ github.event.inputs.environment }}" 
            echo "Branch: ${{ github.event.inputs.branch }}"
        - name: Check out repository build-templates
          uses: actions/checkout@v3
          with:
            repository: 'devops-pro-mota/build-templates'
            ref: 'refs/heads/main'
            gh_token: '${{ secrets.GHTOKEN }}'
            path: 'build-templates/'
  
        # - uses: ./build-templates/.github/workflows/actions/validacoes
        #   name: Metrics Pipeline
        #   with:
        #    ambiente: ${{ secrets.SNOWUSER }}
        #   env:      
        #     solution: ${{ github.event.inputs.solution }}
        #     environment: ${{ github.event.inputs.environment }}
        #     namespace: ${{ github.event.inputs.namespace }}  

           # executa step docker build e push
        - uses: ./build-templates/.github/workflows/release/docker-hub
          name: Docker Build and Push (Release)
          env:      
            environment: ${{ github.event.inputs.environment }}
            projeto: ${{ github.event.repository.name }}
            gh_token: '${{ secrets.GHTOKEN }}'

          #executar step apenas se der erro 
        - uses: ./build-templates/.github/workflows/actions/falha
          name: Falha de execução
          if: ${{ failure() }}
          env:      
            environment: ${{ github.event.inputs.environment }}
            Gmud: ${{ github.event.inputs.Gmud }}
          # executa step apenas se der sucesso
        - uses: ./build-templates/.github/workflows/actions/sucesso
          name: Sucesso de execução
          if: ${{ success() }}
          env:      
            environment: ${{ github.event.inputs.environment }}
            Gmud: ${{ github.event.inputs.Gmud }} 

    deploy-k8s-hml:
      runs-on: linux
      needs: pipeline-build-hml
      steps:
        - name: Check out repository
          uses: actions/checkout@v3
        - run: |
            echo "Env: ${{ github.event.inputs.environment }}" 
            echo "Branch: ${{ github.event.inputs.branch }}"
        - name: Check out repository build-templates
          uses: actions/checkout@v3
          with:
            repository: 'devops-pro-mota/build-templates'
            ref: 'refs/heads/main'
            gh_token: '${{ secrets.GHTOKEN }}'
            path: 'build-templates/'

          # deploy k8s
        - name: Deploy Cluster k8s
          uses: ./build-templates/.github/workflows/release/kubectl
          env:      
            environment: ${{ github.event.inputs.environment }}
            namespace: ${{ github.event.inputs.namespace }}                               

    pipeline-build-prd:
      needs: Validate
      runs-on: linux
      if: ${{ github.event.inputs.environment == 'prd' }}
      steps:
        - name: Check out repository
          uses: actions/checkout@v3
        - run: |
            echo "Env: ${{ github.event.inputs.environment }}" 
            echo "Branch: ${{ github.event.inputs.branch }}"
        - name: Check out repository build-templates
          uses: actions/checkout@v3
          with:
            repository: 'devops-pro-mota/build-templates'
            ref: 'refs/heads/main'
            gh_token: '${{ secrets.GHTOKEN }}'
            path: 'build-templates/'
  
        # - uses: ./build-templates/.github/workflows/actions/validacoes
        #   name: Metrics Pipeline
        #   env:      
        #     environment: ${{ github.event.inputs.environment }}
        #     Gmud: ${{ github.event.inputs.Gmud }}  
          # executa step docker build e push
        - uses: ./build-templates/.github/workflows/release/docker-hub
          name: Docker Build and Push (Release)
          env:      
            environment: ${{ github.event.inputs.environment }}
            projeto: ${{ github.event.repository.name }}
            gh_token: '${{ secrets.GHTOKEN }}'            
                       
        - uses: ./build-templates/.github/workflows/actions/gmud
          name: GMUD-Validate
          env:      
            environment: ${{ github.event.inputs.environment }}
            Gmud: ${{ github.event.inputs.Gmud }}
          #executar step apenas se der erro 
        - uses: ./build-templates/.github/workflows/actions/falha
          name: Falha de execução
          if: ${{ failure() }}
          env:      
            environment: ${{ github.event.inputs.environment }}
            Gmud: ${{ github.event.inputs.Gmud }}
          # executa step apenas se der sucesso
        - uses: ./build-templates/.github/workflows/actions/sucesso
          name: Sucesso de execução
          if: ${{ success() }}
          env:      
            environment: ${{ github.event.inputs.environment }}
            Gmud: ${{ github.event.inputs.Gmud }}    

    deploy-k8s-prd:
      runs-on: linux
      needs: pipeline-build-prd
      steps:
        - name: Check out repository
          uses: actions/checkout@v3
        - run: |
            echo "Env: ${{ github.event.inputs.environment }}" 
            echo "Branch: ${{ github.event.inputs.branch }}"
        - name: Check out repository build-templates
          uses: actions/checkout@v3
          with:
            repository: 'devops-pro-mota/build-templates'
            ref: 'refs/heads/main'
            gh_token: '${{ secrets.GHTOKEN }}'
            path: 'build-templates/'
                  
          # deploy k8s
        - name: Deploy Cluster k8s
          uses: ./build-templates/.github/workflows/release/kubectl
          env:      
            environment: ${{ github.event.inputs.environment }}
            namespace: ${{ github.event.inputs.namespace }}
            gh_token: '${{ secrets.GHTOKEN }}'
         
